/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import TableModelClass.TableModelStudent;
import TableModelClass.TableModelPromotion;
import ClassBdd.Formation;
import ClassBdd.Former;
import ClassBdd.Promotion;
import ClassBdd.School;
import Controller.Controller;
import Controller.Declencheur;
import ImiesException.AddException;
import ImiesException.AddFormerParamsException;
import ImiesException.AddSiteParamsException;
import java.sql.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import TableModelClass.TableModelPromotion;
import TableModelClass.TableModelStudent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author bouessay.cdi02
 */
public class ViewMain extends javax.swing.JFrame implements View{

    /**
     * Creates new form ViewMain
     */
    public ViewMain() {
        initComponents();
    }
    
    
    private void loadListFormation(){
        Controller.getInstance().startScenario(new Declencheur(Declencheur.LOAD_FORMATION, new Formation()));
        Controller.getInstance().startScenario(new Declencheur(Declencheur.LOAD_CITY_NAME,null));
        Controller.getInstance().startScenario(new Declencheur(Declencheur.CHOIX_PROMOTION, new Promotion()));

        Controller.getInstance().startScenario(new Declencheur(Declencheur.LOAD_BEGIN_DATE,null));
        Controller.getInstance().startScenario(new Declencheur(Declencheur.LOAD_END_DATE,null));
        Controller.getInstance().startScenario(new Declencheur(Declencheur.LOAD_SCHOOL, null));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneVueGenerale = new javax.swing.JTabbedPane();
        jPanelAcceuil = new javax.swing.JPanel();
        jScrollPaneAffichageRechercherPromotion = new javax.swing.JScrollPane();
        jTableAffichageRecherchePromotion = new javax.swing.JTable();
        jComboBoxChoixFormationRechercherPromotion = new javax.swing.JComboBox();
        jComboBoxChoixVilleRechercherPromotion = new javax.swing.JComboBox();
        jComboBoxChoixDateDebutRechercherPromotion = new javax.swing.JComboBox();
        jComboBoxChoixDateFinRechercherPromotion = new javax.swing.JComboBox();
        jButtonValiderRechercherPromotion = new javax.swing.JButton();
        jLabelAffichageRecherchePromotionRechercherPromotion = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanelChoisirPromotion = new javax.swing.JPanel();
        jButtonAjouterEtudiantChoixPromotion = new javax.swing.JButton();
        jComboBoxSelectionnerPromotionChoixPromotion = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAffichagePromotioonChoisieChoixPromotion = new javax.swing.JTable();
        jLabelPromotionChoisieChoixPromotion = new javax.swing.JLabel();
        jLabelAffichageChoixPromotionChoixPromotion = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanelAjouterSite = new javax.swing.JPanel();
        jLabelAffichageVilleAjoutSite = new javax.swing.JLabel();
        jLabelAffichageNomDuSiteAjoutSite = new javax.swing.JLabel();
        jTextFieldVilleAjoutSite = new javax.swing.JTextField();
        jTextFieldNomSiteAjoutSite = new javax.swing.JTextField();
        jButtonAnnulerAjoutSite = new javax.swing.JButton();
        jButtonValiderAjoutSite = new javax.swing.JButton();
        jLabelAffichageAjouterSite = new javax.swing.JLabel();
        jPanelAjouterPromotion = new javax.swing.JPanel();
        jComboBoxNomFormationAjouterPromotion = new javax.swing.JComboBox();
        jComboBoxEcoleNomAjouterPromotion = new javax.swing.JComboBox();
        jLabelAffichageAjoutPromotionAjouterPromotion = new javax.swing.JLabel();
        jLabelChoisirLaFormationAjouterPromotion = new javax.swing.JLabel();
        jLabelChoisirLaVilleAjouterPromotion = new javax.swing.JLabel();
        jLabelChoisirDateDebutAjouterPromotion = new javax.swing.JLabel();
        jLabelChoisirDateFinAjouterPromotion = new javax.swing.JLabel();
        jButtonValiderAjoutPromotionAjouterPromotion = new javax.swing.JButton();
        jTextFieldDateDebutAjouterPromotion = new javax.swing.JTextField();
        jTextFieldDateFinAjouterPromotion = new javax.swing.JTextField();
        jPanelGestionDuCompte = new javax.swing.JPanel();
        jButtonValiderGestionCompte = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldChangerIdentifiantGestionCompte = new javax.swing.JTextField();
        jTextFieldChangerMotPasseGestionCompte = new javax.swing.JTextField();
        jTextFieldChangerCoursGestionCompte = new javax.swing.JTextField();
        jLabelAffichageGestionCompteGestionCompte = new javax.swing.JLabel();
        jButtonAjotuerFormateurGestionCompte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTableAffichageRecherchePromotion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nom de Promotion", "Ville", "Numéro de promotion", "Nom de Formation"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPaneAffichageRechercherPromotion.setViewportView(jTableAffichageRecherchePromotion);

        jComboBoxChoixFormationRechercherPromotion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        jComboBoxChoixFormationRechercherPromotion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBoxChoixFormationRechercherPromotionFocusGained(evt);
            }
        });
        jComboBoxChoixFormationRechercherPromotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxChoixFormationRechercherPromotionActionPerformed(evt);
            }
        });

        jComboBoxChoixVilleRechercherPromotion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        jComboBoxChoixVilleRechercherPromotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxChoixVilleRechercherPromotionActionPerformed(evt);
            }
        });

        jComboBoxChoixDateDebutRechercherPromotion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        jComboBoxChoixDateDebutRechercherPromotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxChoixDateDebutRechercherPromotionActionPerformed(evt);
            }
        });

        jComboBoxChoixDateFinRechercherPromotion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        jComboBoxChoixDateFinRechercherPromotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxChoixDateFinRechercherPromotionActionPerformed(evt);
            }
        });

        jButtonValiderRechercherPromotion.setText("Valider");
        jButtonValiderRechercherPromotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderRechercherPromotionActionPerformed(evt);
            }
        });

        jLabelAffichageRecherchePromotionRechercherPromotion.setFont(new java.awt.Font("Yu Mincho Light", 0, 24)); // NOI18N
        jLabelAffichageRecherchePromotionRechercherPromotion.setText("Recherche Promotion");

        jLabel4.setText("Formation");

        jLabel5.setText("Ville");

        jLabel6.setText("Date Début");

        jLabel7.setText("Date Fin");

        javax.swing.GroupLayout jPanelAcceuilLayout = new javax.swing.GroupLayout(jPanelAcceuil);
        jPanelAcceuil.setLayout(jPanelAcceuilLayout);
        jPanelAcceuilLayout.setHorizontalGroup(
            jPanelAcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneAffichageRechercherPromotion, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
            .addGroup(jPanelAcceuilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(30, 30, 30)
                .addGroup(jPanelAcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAcceuilLayout.createSequentialGroup()
                        .addGroup(jPanelAcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxChoixDateFinRechercherPromotion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxChoixFormationRechercherPromotion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelAcceuilLayout.createSequentialGroup()
                        .addGroup(jPanelAcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxChoixDateDebutRechercherPromotion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxChoixVilleRechercherPromotion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonValiderRechercherPromotion)
                        .addGap(46, 46, 46)
                        .addComponent(jLabelAffichageRecherchePromotionRechercherPromotion)
                        .addGap(23, 23, 23))))
        );
        jPanelAcceuilLayout.setVerticalGroup(
            jPanelAcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAcceuilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxChoixFormationRechercherPromotion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAcceuilLayout.createSequentialGroup()
                        .addGroup(jPanelAcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jComboBoxChoixVilleRechercherPromotion, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanelAcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jComboBoxChoixDateDebutRechercherPromotion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelAcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelAffichageRecherchePromotionRechercherPromotion)
                        .addComponent(jButtonValiderRechercherPromotion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxChoixDateFinRechercherPromotion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(6, 6, 6)
                .addComponent(jScrollPaneAffichageRechercherPromotion, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
        );

        jTabbedPaneVueGenerale.addTab("Accueil", jPanelAcceuil);

        jButtonAjouterEtudiantChoixPromotion.setText("Ajouter Etudiant ");
        jButtonAjouterEtudiantChoixPromotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterEtudiantChoixPromotionActionPerformed(evt);
            }
        });

        jComboBoxSelectionnerPromotionChoixPromotion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        jComboBoxSelectionnerPromotionChoixPromotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSelectionnerPromotionChoixPromotionActionPerformed(evt);
            }
        });

        jTableAffichagePromotioonChoisieChoixPromotion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Prénom", "Nom", "Mail", "Age", "N° Tel", "Retards", "Suppr.", "Modif."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableAffichagePromotioonChoisieChoixPromotion);

        jLabelPromotionChoisieChoixPromotion.setFont(new java.awt.Font("Yu Mincho", 0, 18)); // NOI18N

        jLabelAffichageChoixPromotionChoixPromotion.setFont(new java.awt.Font("Yu Mincho Light", 0, 24)); // NOI18N
        jLabelAffichageChoixPromotionChoixPromotion.setText("Choix Promotion");

        jLabel8.setText("Choisir nom de Promotion :");

        javax.swing.GroupLayout jPanelChoisirPromotionLayout = new javax.swing.GroupLayout(jPanelChoisirPromotion);
        jPanelChoisirPromotion.setLayout(jPanelChoisirPromotionLayout);
        jPanelChoisirPromotionLayout.setHorizontalGroup(
            jPanelChoisirPromotionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelChoisirPromotionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(133, 133, 133)
                .addComponent(jLabelAffichageChoixPromotionChoixPromotion)
                .addGap(163, 163, 163)
                .addComponent(jLabelPromotionChoisieChoixPromotion, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(jPanelChoisirPromotionLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jComboBoxSelectionnerPromotionChoixPromotion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAjouterEtudiantChoixPromotion)
                .addGap(42, 42, 42))
        );
        jPanelChoisirPromotionLayout.setVerticalGroup(
            jPanelChoisirPromotionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChoisirPromotionLayout.createSequentialGroup()
                .addGroup(jPanelChoisirPromotionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelChoisirPromotionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelPromotionChoisieChoixPromotion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelChoisirPromotionLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelChoisirPromotionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAffichageChoixPromotionChoixPromotion)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanelChoisirPromotionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSelectionnerPromotionChoixPromotion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAjouterEtudiantChoixPromotion))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        jTabbedPaneVueGenerale.addTab("Choisir Promotion", jPanelChoisirPromotion);

        jLabelAffichageVilleAjoutSite.setText("Ville :");

        jLabelAffichageNomDuSiteAjoutSite.setText("Nom du site  :");

        jButtonAnnulerAjoutSite.setText("Annuler");

        jButtonValiderAjoutSite.setText("Valider");
        jButtonValiderAjoutSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderAjoutSiteActionPerformed(evt);
            }
        });

        jLabelAffichageAjouterSite.setFont(new java.awt.Font("Yu Mincho Light", 0, 24)); // NOI18N
        jLabelAffichageAjouterSite.setText("Ajouter un Site école :");

        javax.swing.GroupLayout jPanelAjouterSiteLayout = new javax.swing.GroupLayout(jPanelAjouterSite);
        jPanelAjouterSite.setLayout(jPanelAjouterSiteLayout);
        jPanelAjouterSiteLayout.setHorizontalGroup(
            jPanelAjouterSiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAjouterSiteLayout.createSequentialGroup()
                .addContainerGap(275, Short.MAX_VALUE)
                .addGroup(jPanelAjouterSiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAjouterSiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelAffichageAjouterSite)
                        .addGroup(jPanelAjouterSiteLayout.createSequentialGroup()
                            .addGroup(jPanelAjouterSiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelAffichageNomDuSiteAjoutSite)
                                .addComponent(jLabelAffichageVilleAjoutSite))
                            .addGap(57, 57, 57)
                            .addGroup(jPanelAjouterSiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldNomSiteAjoutSite, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldVilleAjoutSite, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAjouterSiteLayout.createSequentialGroup()
                        .addComponent(jButtonAnnulerAjoutSite)
                        .addGap(108, 108, 108)
                        .addComponent(jButtonValiderAjoutSite)))
                .addGap(280, 280, 280))
        );
        jPanelAjouterSiteLayout.setVerticalGroup(
            jPanelAjouterSiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAjouterSiteLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabelAffichageAjouterSite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addGroup(jPanelAjouterSiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldVilleAjoutSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAffichageVilleAjoutSite))
                .addGap(41, 41, 41)
                .addGroup(jPanelAjouterSiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomSiteAjoutSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAffichageNomDuSiteAjoutSite))
                .addGap(56, 56, 56)
                .addGroup(jPanelAjouterSiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonValiderAjoutSite)
                    .addComponent(jButtonAnnulerAjoutSite))
                .addGap(115, 115, 115))
        );

        jTabbedPaneVueGenerale.addTab("Ajouter site", jPanelAjouterSite);

        jComboBoxNomFormationAjouterPromotion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));

        jComboBoxEcoleNomAjouterPromotion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));

        jLabelAffichageAjoutPromotionAjouterPromotion.setFont(new java.awt.Font("Yu Mincho Light", 0, 24)); // NOI18N
        jLabelAffichageAjoutPromotionAjouterPromotion.setText("Ajouter une Promotion");

        jLabelChoisirLaFormationAjouterPromotion.setFont(new java.awt.Font("Yu Mincho", 0, 12)); // NOI18N
        jLabelChoisirLaFormationAjouterPromotion.setText("Choisir la formation :");

        jLabelChoisirLaVilleAjouterPromotion.setFont(new java.awt.Font("Yu Mincho", 0, 12)); // NOI18N
        jLabelChoisirLaVilleAjouterPromotion.setText("Choisir l'école :");

        jLabelChoisirDateDebutAjouterPromotion.setFont(new java.awt.Font("Yu Mincho", 0, 12)); // NOI18N
        jLabelChoisirDateDebutAjouterPromotion.setText("Choisir date début :");

        jLabelChoisirDateFinAjouterPromotion.setFont(new java.awt.Font("Yu Mincho", 0, 12)); // NOI18N
        jLabelChoisirDateFinAjouterPromotion.setText("Choisir date fin :");

        jButtonValiderAjoutPromotionAjouterPromotion.setFont(new java.awt.Font("Yu Mincho", 0, 12)); // NOI18N
        jButtonValiderAjoutPromotionAjouterPromotion.setText("Valider");
        jButtonValiderAjoutPromotionAjouterPromotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderAjoutPromotionAjouterPromotionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAjouterPromotionLayout = new javax.swing.GroupLayout(jPanelAjouterPromotion);
        jPanelAjouterPromotion.setLayout(jPanelAjouterPromotionLayout);
        jPanelAjouterPromotionLayout.setHorizontalGroup(
            jPanelAjouterPromotionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAjouterPromotionLayout.createSequentialGroup()
                .addGroup(jPanelAjouterPromotionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAjouterPromotionLayout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jLabelAffichageAjoutPromotionAjouterPromotion))
                    .addGroup(jPanelAjouterPromotionLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addGroup(jPanelAjouterPromotionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxEcoleNomAjouterPromotion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelAjouterPromotionLayout.createSequentialGroup()
                                .addGroup(jPanelAjouterPromotionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabelChoisirLaFormationAjouterPromotion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelChoisirDateDebutAjouterPromotion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelChoisirLaVilleAjouterPromotion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelChoisirDateFinAjouterPromotion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(111, 111, 111)
                                .addGroup(jPanelAjouterPromotionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxNomFormationAjouterPromotion, 0, 80, Short.MAX_VALUE)
                                    .addComponent(jTextFieldDateDebutAjouterPromotion)
                                    .addComponent(jTextFieldDateFinAjouterPromotion)))))
                    .addGroup(jPanelAjouterPromotionLayout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(jButtonValiderAjoutPromotionAjouterPromotion)))
                .addContainerGap(308, Short.MAX_VALUE))
        );
        jPanelAjouterPromotionLayout.setVerticalGroup(
            jPanelAjouterPromotionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAjouterPromotionLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabelAffichageAjoutPromotionAjouterPromotion)
                .addGap(62, 62, 62)
                .addGroup(jPanelAjouterPromotionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxNomFormationAjouterPromotion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelChoisirLaFormationAjouterPromotion))
                .addGap(18, 18, 18)
                .addGroup(jPanelAjouterPromotionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxEcoleNomAjouterPromotion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelChoisirLaVilleAjouterPromotion))
                .addGap(18, 18, 18)
                .addGroup(jPanelAjouterPromotionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelChoisirDateDebutAjouterPromotion)
                    .addComponent(jTextFieldDateDebutAjouterPromotion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAjouterPromotionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelChoisirDateFinAjouterPromotion)
                    .addComponent(jTextFieldDateFinAjouterPromotion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButtonValiderAjoutPromotionAjouterPromotion)
                .addGap(97, 97, 97))
        );

        jTabbedPaneVueGenerale.addTab("Ajouter Promotion", jPanelAjouterPromotion);

        jButtonValiderGestionCompte.setText("Valider");
        jButtonValiderGestionCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderGestionCompteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Mincho", 0, 12)); // NOI18N
        jLabel1.setText("Nouvel identifiant :");

        jLabel2.setFont(new java.awt.Font("Yu Mincho", 0, 12)); // NOI18N
        jLabel2.setText("Nouveau mot de Passe :");

        jLabel3.setFont(new java.awt.Font("Yu Mincho", 0, 12)); // NOI18N
        jLabel3.setText("Nouveau Cours :");

        jLabelAffichageGestionCompteGestionCompte.setFont(new java.awt.Font("Yu Mincho Light", 0, 24)); // NOI18N
        jLabelAffichageGestionCompteGestionCompte.setText("Gestion de Compte");

        jButtonAjotuerFormateurGestionCompte.setText("Ajouter un formateur");
        jButtonAjotuerFormateurGestionCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjotuerFormateurGestionCompteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelGestionDuCompteLayout = new javax.swing.GroupLayout(jPanelGestionDuCompte);
        jPanelGestionDuCompte.setLayout(jPanelGestionDuCompteLayout);
        jPanelGestionDuCompteLayout.setHorizontalGroup(
            jPanelGestionDuCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGestionDuCompteLayout.createSequentialGroup()
                .addGroup(jPanelGestionDuCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGestionDuCompteLayout.createSequentialGroup()
                        .addGap(28, 300, Short.MAX_VALUE)
                        .addGroup(jPanelGestionDuCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanelGestionDuCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldChangerIdentifiantGestionCompte, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(jTextFieldChangerMotPasseGestionCompte)
                            .addComponent(jTextFieldChangerCoursGestionCompte)))
                    .addGroup(jPanelGestionDuCompteLayout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabelAffichageGestionCompteGestionCompte)))
                .addGap(221, 221, 221))
            .addGroup(jPanelGestionDuCompteLayout.createSequentialGroup()
                .addGroup(jPanelGestionDuCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGestionDuCompteLayout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(jButtonValiderGestionCompte))
                    .addGroup(jPanelGestionDuCompteLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButtonAjotuerFormateurGestionCompte)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelGestionDuCompteLayout.setVerticalGroup(
            jPanelGestionDuCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGestionDuCompteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAffichageGestionCompteGestionCompte)
                .addGap(11, 11, 11)
                .addComponent(jButtonAjotuerFormateurGestionCompte)
                .addGap(31, 31, 31)
                .addGroup(jPanelGestionDuCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldChangerIdentifiantGestionCompte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelGestionDuCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldChangerMotPasseGestionCompte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelGestionDuCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldChangerCoursGestionCompte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jButtonValiderGestionCompte)
                .addGap(168, 168, 168))
        );

        jTabbedPaneVueGenerale.addTab("Gestion du compte", jPanelGestionDuCompte);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneVueGenerale)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneVueGenerale, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPaneVueGenerale.getAccessibleContext().setAccessibleName("Accueil");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValiderAjoutSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderAjoutSiteActionPerformed
        School sc = new School();
        sc.setSchoolCity(jTextFieldVilleAjoutSite.getText());
        sc.setSchoolName(jTextFieldNomSiteAjoutSite.getText());
        Controller.getInstance().startScenario(new Declencheur(Declencheur.AJOUT_SCHOOL, sc));
    }//GEN-LAST:event_jButtonValiderAjoutSiteActionPerformed

    private void jButtonValiderRechercherPromotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderRechercherPromotionActionPerformed
        Promotion promo = new Promotion();
        //promo.setFormationId(((Formation)this.jComboBoxChoixFormationRechercherPromotion.getSelectedItem()).getFormationId());
    }//GEN-LAST:event_jButtonValiderRechercherPromotionActionPerformed

    private void jButtonAjotuerFormateurGestionCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjotuerFormateurGestionCompteActionPerformed
        ViewAddFormer viewAddFormer = new ViewAddFormer();
        viewAddFormer.setVisible(true);
    }//GEN-LAST:event_jButtonAjotuerFormateurGestionCompteActionPerformed

    private void jButtonValiderGestionCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderGestionCompteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonValiderGestionCompteActionPerformed

    private void jButtonValiderAjoutPromotionAjouterPromotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderAjoutPromotionAjouterPromotionActionPerformed

        Controller.getInstance().startScenario(new Declencheur(Declencheur.SEARCH_IDSCHOOL_WITH_NAME,
                jTextFieldDateDebutAjouterPromotion.getText(),
                jTextFieldDateFinAjouterPromotion.getText(),
                jComboBoxEcoleNomAjouterPromotion.getSelectedItem().toString(),
                jComboBoxNomFormationAjouterPromotion.getSelectedItem().toString()));
        
        
    }//GEN-LAST:event_jButtonValiderAjoutPromotionAjouterPromotionActionPerformed

    private void jButtonAjouterEtudiantChoixPromotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterEtudiantChoixPromotionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAjouterEtudiantChoixPromotionActionPerformed

    private void jComboBoxSelectionnerPromotionChoixPromotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSelectionnerPromotionChoixPromotionActionPerformed
        // TODO add your handling code here:
        
        Controller.getInstance().startScenario(new Declencheur(Declencheur.AFFICHAGE_PROMOTION_CHOISIE,new Student()));       
    }//GEN-LAST:event_jComboBoxSelectionnerPromotionChoixPromotionActionPerformed

    private void jComboBoxChoixFormationRechercherPromotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxChoixFormationRechercherPromotionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxChoixFormationRechercherPromotionActionPerformed

    private void jComboBoxChoixVilleRechercherPromotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxChoixVilleRechercherPromotionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxChoixVilleRechercherPromotionActionPerformed

    private void jComboBoxChoixDateDebutRechercherPromotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxChoixDateDebutRechercherPromotionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxChoixDateDebutRechercherPromotionActionPerformed

    private void jComboBoxChoixDateFinRechercherPromotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxChoixDateFinRechercherPromotionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxChoixDateFinRechercherPromotionActionPerformed

    private void jComboBoxChoixFormationRechercherPromotionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxChoixFormationRechercherPromotionFocusGained
        
    }//GEN-LAST:event_jComboBoxChoixFormationRechercherPromotionFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjotuerFormateurGestionCompte;
    private javax.swing.JButton jButtonAjouterEtudiantChoixPromotion;
    private javax.swing.JButton jButtonAnnulerAjoutSite;
    private javax.swing.JButton jButtonValiderAjoutPromotionAjouterPromotion;
    private javax.swing.JButton jButtonValiderAjoutSite;
    private javax.swing.JButton jButtonValiderGestionCompte;
    private javax.swing.JButton jButtonValiderRechercherPromotion;
    private javax.swing.JComboBox jComboBoxChoixDateDebutRechercherPromotion;
    private javax.swing.JComboBox jComboBoxChoixDateFinRechercherPromotion;
    private javax.swing.JComboBox jComboBoxChoixFormationRechercherPromotion;
    private javax.swing.JComboBox jComboBoxChoixVilleRechercherPromotion;
    private javax.swing.JComboBox jComboBoxEcoleNomAjouterPromotion;
    private javax.swing.JComboBox jComboBoxNomFormationAjouterPromotion;
    private javax.swing.JComboBox jComboBoxSelectionnerPromotionChoixPromotion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelAffichageAjoutPromotionAjouterPromotion;
    private javax.swing.JLabel jLabelAffichageAjouterSite;
    private javax.swing.JLabel jLabelAffichageChoixPromotionChoixPromotion;
    private javax.swing.JLabel jLabelAffichageGestionCompteGestionCompte;
    private javax.swing.JLabel jLabelAffichageNomDuSiteAjoutSite;
    private javax.swing.JLabel jLabelAffichageRecherchePromotionRechercherPromotion;
    private javax.swing.JLabel jLabelAffichageVilleAjoutSite;
    private javax.swing.JLabel jLabelChoisirDateDebutAjouterPromotion;
    private javax.swing.JLabel jLabelChoisirDateFinAjouterPromotion;
    private javax.swing.JLabel jLabelChoisirLaFormationAjouterPromotion;
    private javax.swing.JLabel jLabelChoisirLaVilleAjouterPromotion;
    private javax.swing.JLabel jLabelPromotionChoisieChoixPromotion;
    private javax.swing.JPanel jPanelAcceuil;
    private javax.swing.JPanel jPanelAjouterPromotion;
    private javax.swing.JPanel jPanelAjouterSite;
    private javax.swing.JPanel jPanelChoisirPromotion;
    private javax.swing.JPanel jPanelGestionDuCompte;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneAffichageRechercherPromotion;
    private javax.swing.JTabbedPane jTabbedPaneVueGenerale;
    private javax.swing.JTable jTableAffichagePromotioonChoisieChoixPromotion;
    private javax.swing.JTable jTableAffichageRecherchePromotion;
    private javax.swing.JTextField jTextFieldChangerCoursGestionCompte;
    private javax.swing.JTextField jTextFieldChangerIdentifiantGestionCompte;
    private javax.swing.JTextField jTextFieldChangerMotPasseGestionCompte;
    private javax.swing.JTextField jTextFieldDateDebutAjouterPromotion;
    private javax.swing.JTextField jTextFieldDateFinAjouterPromotion;
    private javax.swing.JTextField jTextFieldNomSiteAjoutSite;
    private javax.swing.JTextField jTextFieldVilleAjoutSite;
    // End of variables declaration//GEN-END:variables

    public void AddSiteMessage(Object msg) {
        if (msg instanceof AddException) {
            javax.swing.JOptionPane.showMessageDialog(null,((AddException)msg).getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        else if (msg instanceof String) {
            javax.swing.JOptionPane.showMessageDialog(null,msg);
        }
        else if (msg instanceof AddSiteParamsException){
            javax.swing.JOptionPane.showMessageDialog(null,((AddSiteParamsException)msg).getMessage(),"Warning",JOptionPane.WARNING_MESSAGE);
        }
    }
    
    public void AddFormerMessage(Object msg){
        if (msg instanceof AddFormerParamsException){
            javax.swing.JOptionPane.showMessageDialog(null,((AddFormerParamsException)msg).getMessage(), "Warning",JOptionPane.WARNING_MESSAGE );
        }
    }

    public void ChargeListFormation(List<Formation> listForma) {
        for (Formation forma : listForma) {
            jComboBoxChoixFormationRechercherPromotion.addItem(forma);
            jComboBoxNomFormationAjouterPromotion.addItem(forma);
        }
    }

    public void init() {
        
        loadListFormation();
        
        
        
        this.setVisible(true);
    }
    public void chargeListePromotion(List<Promotion> listePromo){
        for (Promotion promo : listePromo) {
            jComboBoxSelectionnerPromotionChoixPromotion.addItem(promo);
        }
    }

    
    public void ChargeListSchoolName(List<String> listSchool)
    {
        for(String s : listSchool){
            jComboBoxEcoleNomAjouterPromotion.addItem(s);
        }
    }
    public void ChargeListCity(List<String> listCity) {
        for (String s : listCity) {
            jComboBoxChoixVilleRechercherPromotion.addItem(s);
        }
    }

    public void LoadDateBegin(List<Date> listDateBegin) {
        for (Date s : listDateBegin) {
            jComboBoxChoixDateDebutRechercherPromotion.addItem(s.toString());
        }
    }

    public void LoadDateEnd(List<Date> listDateEnd) {
        for (Date s : listDateEnd) {
            jComboBoxChoixDateFinRechercherPromotion.addItem(s.toString());
        }
    }    
    public void LoadSchoolName(List<String> listSchoolName) {
        for (String s : listSchoolName) {
            jComboBoxEcoleNomAjouterPromotion.addItem(s);
        }
    }

    public void affichageTablePromotionChoisie(List<Student> listStudent) {
        TableModel tableModel = new TableModelStudent(listStudent);
        
        jTableAffichagePromotionChoisieChoixPromotion.setModel(tableModel);
            
            
    }    

    public void chargePromoJTable(List<Promotion> listPromo) {
        TableModel model = new TableModelPromotion(listPromo);
        jTableAffichageRecherchePromotion.insets();
        jTableAffichageRecherchePromotion.setModel(model);
    }
}
